#############################################################################
# Makefile for building: felgo_statusbar.app/Contents/MacOS/felgo_statusbar
# Generated by qmake (3.1) (Qt 5.15.2)
# Project:  felgo_statusbar.pro
# Template: app
# Command: /Users/marekflorianczyk/Felgo/Felgo/ios/bin/qmake -o felgo_statusbar.xcodeproj/project.pbxproj felgo_statusbar.pro -spec macx-xcode
#############################################################################

MAKEFILE      = project.pbxproj

EQ            = =

QMAKE    = /Users/marekflorianczyk/Felgo/Felgo/ios/bin/qmake
felgo_statusbar.xcodeproj/project.pbxproj: felgo_statusbar.pro /Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/macx-ios-clang/qmake.conf /Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/spec_pre.prf \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/qdevice.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/device_config.prf \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/common/unix.conf \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/common/mac.conf \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/common/uikit.conf \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/common/ios.conf \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/common/sanitize.conf \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/common/gcc-base.conf \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/common/gcc-base-mac.conf \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/common/clang.conf \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/common/clang-mac.conf \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/common/uikit/clang.conf \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/common/uikit/qmake.conf \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/qconfig.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_3danimation.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_3danimation_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_3dcore.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_3dextras.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_3dinput.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_3dlogic.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_3dquick.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_3drender.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_3drender_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_bluetooth.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_charts.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_charts_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_core.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_core_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_datavisualization.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_edid_support_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_gamepad.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_gamepad_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_gui.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_help.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_help_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_location.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_location_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_macextras.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_macextras_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_network.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_network_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_networkauth.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_networkauth_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_nfc.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_nfc_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_opengl.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_openglextensions.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_positioning.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_positioning_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_positioningquick.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_purchasing.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_purchasing_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_qml.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_qmlmodels.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_quick.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_remoteobjects.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_repparser.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_repparser_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_scxml.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_scxml_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_sensors.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_sensors_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_sql.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_svg.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_testlib.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_texttospeech.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_theme_support_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_uiplugin.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_uitools.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_webchannel.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_websockets.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_websockets_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_webview.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_webview_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_widgets.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_xml.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_zlib_private.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_darwingamepad.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_defaultgeometryloader.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_gltfgeometryloader.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_gltfsceneexport.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_gltfsceneimport.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_openglrenderer.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qavfcamera.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qavfmediaplayer.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qgif.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qicns.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qico.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qios.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qiosnsphotolibrarysupport.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qjpeg.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qmacheif.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qmacjp2.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qminimal.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qmldbg_debugger.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qmldbg_inspector.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qmldbg_local.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qmldbg_messages.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qmldbg_native.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qmldbg_nativedebugger.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qmldbg_preview.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qmldbg_profiler.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qmldbg_quickprofiler.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qmldbg_server.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qmldbg_tcp.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qoffscreen.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qsqlite.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qsvg.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qsvgicon.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qtaudio_coreaudio.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qtexttospeech_speechios.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qtga.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qtgeoservices_esri.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qtgeoservices_itemsoverlay.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qtgeoservices_mapbox.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qtgeoservices_mapboxgl.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qtgeoservices_nokia.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qtgeoservices_osm.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qtiff.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qtposition_cl.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qtsensors_generic.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qtsensors_ios.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qtwebview_darwin.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qwbmp.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qwebp.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_scene2d.pri \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/qt_functions.prf \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/qt_config.prf \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/macx-ios-clang/qmake.conf \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/macx-xcode/qmake.conf \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/spec_post.prf \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/exclusive_builds.prf \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/mac/sdk.prf \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/uikit/sdk.prf \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/toolchain.prf \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/mac/toolchain.prf \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/default_pre.prf \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/mac/default_pre.prf \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/uikit/default_pre.prf \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/resolve_config.prf \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/uikit/resolve_config.prf \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/default_post.prf \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/mac/default_post.prf \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/uikit/default_post.prf \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/macx-ios-clang/features/default_post.prf \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/mac/objective_c.prf \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/felgo.prf \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/mac/mac.prf \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/uikit/bitcode.prf \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/warn_on.prf \
		/Users/marekflorianczyk/Felgo/Felgo/ios/plugins/platforms/libqios.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/qt.prf \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/uikit/qt.prf \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/uikit/gc_binaries.prf \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/resources_functions.prf \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/resources.prf \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/moc.prf \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/unix/opengl.prf \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/uic.prf \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/unix/thread.prf \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/qmake_use.prf \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/file_copies.prf \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/mac/rez.prf \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/resolve_target.prf \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/mac/asset_catalogs.prf \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/testcase_targets.prf \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/uikit/testcase_targets.prf \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/exceptions.prf \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/yacc.prf \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/lex.prf \
		felgo_statusbar.pro \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/macx-ios-clang/Default-568h@2x.png \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/macx-ios-clang/LaunchScreen.storyboard \
		/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/common/felgo/resources_user.qrc \
		/Users/marekflorianczyk/Felgo/Felgo/ios/lib/libQt5FontDatabaseSupport.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/lib/libqtfreetype.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/lib/libQt5GraphicsSupport.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/lib/libQt5ClipboardSupport.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/lib/libQt5Gui.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/lib/libqtlibpng.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/lib/libqtharfbuzz.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/lib/libQt5Core.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/lib/libqtpcre2.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/plugins/platforms/darwin/libqiosnsphotolibrarysupport.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/plugins/mediaservice/libqavfcamera.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/plugins/mediaservice/libqavfmediaplayer.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/plugins/mediaservice/libqtmedia_audioengine.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/plugins/audio/libqtaudio_coreaudio.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/plugins/playlistformats/libqtmultimedia_m3u.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/plugins/imageformats/libqgif.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/plugins/imageformats/libqicns.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/plugins/imageformats/libqico.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/plugins/imageformats/libqjpeg.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/plugins/imageformats/libqmacheif.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/plugins/imageformats/libqmacjp2.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/plugins/imageformats/libqtga.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/plugins/imageformats/libqtiff.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/plugins/imageformats/libqwbmp.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/plugins/imageformats/libqwebp.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/plugins/qmltooling/libqmldbg_debugger.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/plugins/qmltooling/libqmldbg_inspector.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/plugins/qmltooling/libqmldbg_local.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/plugins/qmltooling/libqmldbg_messages.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/plugins/qmltooling/libqmldbg_native.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/plugins/qmltooling/libqmldbg_nativedebugger.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/plugins/qmltooling/libqmldbg_preview.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/plugins/qmltooling/libqmldbg_profiler.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/plugins/qmltooling/libqmldbg_quickprofiler.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/plugins/qmltooling/libqmldbg_server.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/plugins/qmltooling/libqmldbg_tcp.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/plugins/bearer/libqgenericbearer.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/plugins/sqldrivers/libqsqlite.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/lib/libQt5Quick.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/lib/libQt5Widgets.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/lib/libQt5Multimedia.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/lib/libQt5QmlModels.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/lib/libQt5Qml.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/lib/libQt5WebSockets.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/lib/libQt5Network.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/lib/libQt5Sql.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/lib/libQt5Bluetooth.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/qml/QtQuick.2/libqtquick2plugin.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/qml/QtQml/libqmlplugin.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/qml/QtQml/Models.2/libmodelsplugin.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/qml/QtQml/WorkerScript.2/libworkerscriptplugin.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/qml/QtQuick/Controls/libqtquickcontrolsplugin.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/qml/QtQuick/Window.2/libwindowplugin.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/qml/QtQuick/Layouts/libqquicklayoutsplugin.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/qml/QtGraphicalEffects/libqtgraphicaleffectsplugin.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/qml/QtGraphicalEffects/private/libqtgraphicaleffectsprivate.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/qml/QtLocation/libdeclarative_location.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/qml/QtPositioning/libdeclarative_positioning.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/qml/QtQuick/Controls.2/libqtquickcontrols2plugin.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/qml/QtQuick/Templates.2/libqtquicktemplates2plugin.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/qml/QtWebView/libdeclarative_webview.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/qml/QtQuick/Controls.2/Material/libqtquickcontrols2materialstyleplugin.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/qml/QtQuick/Controls.2/Fusion/libqtquickcontrols2fusionstyleplugin.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/qml/QtQuick/Controls.2/Universal/libqtquickcontrols2universalstyleplugin.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/qml/QtQuick/Controls.2/Imagine/libqtquickcontrols2imaginestyleplugin.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/qml/QtMultimedia/libdeclarative_multimedia.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/qml/QtQuick/LocalStorage/libqmllocalstorageplugin.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/qml/QtQuick/Particles.2/libparticlesplugin.prl \
		/Users/marekflorianczyk/Felgo/Felgo/ios/qml/Qt/labs/settings/libqmlsettingsplugin.prl
	$(QMAKE) -o felgo_statusbar.xcodeproj/project.pbxproj felgo_statusbar.pro -spec macx-xcode
	@echo 'warning: Xcode project has been regenerated, custom settings have been lost. Use CONFIG+=no_autoqmake to prevent this behavior in the future, at the cost of requiring manual project change tracking.'
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/spec_pre.prf:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/qdevice.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/device_config.prf:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/common/unix.conf:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/common/mac.conf:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/common/uikit.conf:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/common/ios.conf:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/common/sanitize.conf:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/common/gcc-base.conf:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/common/gcc-base-mac.conf:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/common/clang.conf:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/common/clang-mac.conf:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/common/uikit/clang.conf:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/common/uikit/qmake.conf:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/qconfig.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_3danimation.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_3danimation_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_3dcore.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_3dcore_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_3dextras.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_3dextras_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_3dinput.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_3dinput_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_3dlogic.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_3dlogic_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_3dquick.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_3dquick_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_3dquickanimation.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_3dquickextras.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_3dquickinput.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_3dquickrender.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_3drender.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_3drender_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_bluetooth.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_bluetooth_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_bodymovin_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_bootstrap_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_charts.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_charts_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_clipboard_support_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_concurrent.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_concurrent_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_core.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_core_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_datavisualization.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_datavisualization_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_edid_support_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_fb_support_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_gamepad.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_gamepad_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_graphics_support_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_gui.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_gui_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_help.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_help_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_location.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_location_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_macextras.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_macextras_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_multimedia.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_multimedia_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_network.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_network_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_networkauth.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_networkauth_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_nfc.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_nfc_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_opengl.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_opengl_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_openglextensions.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_openglextensions_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_positioning.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_positioning_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_positioningquick.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_positioningquick_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_purchasing.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_purchasing_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_qml.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_qml_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_qmldebug_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_qmlmodels.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_qmltest.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_qmltest_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_quick.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_quick_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_quickcontrols2.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_quickshapes_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_quicktemplates2.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_quickwidgets.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_remoteobjects.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_repparser.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_repparser_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_scxml.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_scxml_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_sensors.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_sensors_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_sql.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_sql_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_svg.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_svg_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_testlib.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_testlib_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_texttospeech.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_texttospeech_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_theme_support_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_uiplugin.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_uitools.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_uitools_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_webchannel.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_webchannel_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_websockets.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_websockets_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_webview.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_webview_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_widgets.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_widgets_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_xml.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_xml_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_lib_zlib_private.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_darwingamepad.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_defaultgeometryloader.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_gltfgeometryloader.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_gltfsceneexport.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_gltfsceneimport.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_openglrenderer.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qavfcamera.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qavfmediaplayer.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qgenericbearer.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qgif.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qicns.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qico.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qios.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qiosnsphotolibrarysupport.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qjpeg.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qmacheif.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qmacjp2.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qminimal.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qmldbg_debugger.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qmldbg_inspector.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qmldbg_local.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qmldbg_messages.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qmldbg_native.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qmldbg_nativedebugger.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qmldbg_preview.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qmldbg_profiler.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qmldbg_quickprofiler.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qmldbg_server.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qmldbg_tcp.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qoffscreen.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qsqlite.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qsvg.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qsvgicon.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qtaudio_coreaudio.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qtexttospeech_speechios.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qtga.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qtgeoservices_esri.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qtgeoservices_itemsoverlay.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qtgeoservices_mapbox.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qtgeoservices_mapboxgl.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qtgeoservices_nokia.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qtgeoservices_osm.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qtiff.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qtposition_cl.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qtsensors_generic.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qtsensors_ios.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qtwebview_darwin.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qwbmp.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_qwebp.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/modules/qt_plugin_scene2d.pri:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/qt_functions.prf:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/qt_config.prf:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/macx-ios-clang/qmake.conf:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/macx-xcode/qmake.conf:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/spec_post.prf:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/exclusive_builds.prf:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/mac/sdk.prf:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/uikit/sdk.prf:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/toolchain.prf:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/mac/toolchain.prf:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/default_pre.prf:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/mac/default_pre.prf:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/uikit/default_pre.prf:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/resolve_config.prf:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/uikit/resolve_config.prf:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/default_post.prf:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/mac/default_post.prf:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/uikit/default_post.prf:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/macx-ios-clang/features/default_post.prf:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/mac/objective_c.prf:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/felgo.prf:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/mac/mac.prf:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/uikit/bitcode.prf:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/warn_on.prf:
/Users/marekflorianczyk/Felgo/Felgo/ios/plugins/platforms/libqios.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/qt.prf:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/uikit/qt.prf:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/uikit/gc_binaries.prf:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/resources_functions.prf:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/resources.prf:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/moc.prf:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/unix/opengl.prf:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/uic.prf:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/unix/thread.prf:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/qmake_use.prf:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/file_copies.prf:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/mac/rez.prf:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/resolve_target.prf:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/mac/asset_catalogs.prf:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/testcase_targets.prf:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/uikit/testcase_targets.prf:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/exceptions.prf:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/yacc.prf:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/features/lex.prf:
felgo_statusbar.pro:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/macx-ios-clang/Default-568h@2x.png:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/macx-ios-clang/LaunchScreen.storyboard:
/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/common/felgo/resources_user.qrc:
/Users/marekflorianczyk/Felgo/Felgo/ios/lib/libQt5FontDatabaseSupport.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/lib/libqtfreetype.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/lib/libQt5GraphicsSupport.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/lib/libQt5ClipboardSupport.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/lib/libQt5Gui.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/lib/libqtlibpng.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/lib/libqtharfbuzz.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/lib/libQt5Core.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/lib/libqtpcre2.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/plugins/platforms/darwin/libqiosnsphotolibrarysupport.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/plugins/mediaservice/libqavfcamera.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/plugins/mediaservice/libqavfmediaplayer.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/plugins/mediaservice/libqtmedia_audioengine.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/plugins/audio/libqtaudio_coreaudio.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/plugins/playlistformats/libqtmultimedia_m3u.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/plugins/imageformats/libqgif.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/plugins/imageformats/libqicns.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/plugins/imageformats/libqico.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/plugins/imageformats/libqjpeg.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/plugins/imageformats/libqmacheif.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/plugins/imageformats/libqmacjp2.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/plugins/imageformats/libqtga.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/plugins/imageformats/libqtiff.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/plugins/imageformats/libqwbmp.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/plugins/imageformats/libqwebp.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/plugins/qmltooling/libqmldbg_debugger.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/plugins/qmltooling/libqmldbg_inspector.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/plugins/qmltooling/libqmldbg_local.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/plugins/qmltooling/libqmldbg_messages.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/plugins/qmltooling/libqmldbg_native.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/plugins/qmltooling/libqmldbg_nativedebugger.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/plugins/qmltooling/libqmldbg_preview.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/plugins/qmltooling/libqmldbg_profiler.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/plugins/qmltooling/libqmldbg_quickprofiler.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/plugins/qmltooling/libqmldbg_server.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/plugins/qmltooling/libqmldbg_tcp.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/plugins/bearer/libqgenericbearer.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/plugins/sqldrivers/libqsqlite.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/lib/libQt5Quick.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/lib/libQt5Widgets.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/lib/libQt5Multimedia.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/lib/libQt5QmlModels.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/lib/libQt5Qml.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/lib/libQt5WebSockets.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/lib/libQt5Network.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/lib/libQt5Sql.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/lib/libQt5Bluetooth.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/qml/QtQuick.2/libqtquick2plugin.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/qml/QtQml/libqmlplugin.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/qml/QtQml/Models.2/libmodelsplugin.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/qml/QtQml/WorkerScript.2/libworkerscriptplugin.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/qml/QtQuick/Controls/libqtquickcontrolsplugin.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/qml/QtQuick/Window.2/libwindowplugin.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/qml/QtQuick/Layouts/libqquicklayoutsplugin.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/qml/QtGraphicalEffects/libqtgraphicaleffectsplugin.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/qml/QtGraphicalEffects/private/libqtgraphicaleffectsprivate.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/qml/QtLocation/libdeclarative_location.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/qml/QtPositioning/libdeclarative_positioning.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/qml/QtQuick/Controls.2/libqtquickcontrols2plugin.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/qml/QtQuick/Templates.2/libqtquicktemplates2plugin.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/qml/QtWebView/libdeclarative_webview.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/qml/QtQuick/Controls.2/Material/libqtquickcontrols2materialstyleplugin.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/qml/QtQuick/Controls.2/Fusion/libqtquickcontrols2fusionstyleplugin.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/qml/QtQuick/Controls.2/Universal/libqtquickcontrols2universalstyleplugin.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/qml/QtQuick/Controls.2/Imagine/libqtquickcontrols2imaginestyleplugin.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/qml/QtMultimedia/libdeclarative_multimedia.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/qml/QtQuick/LocalStorage/libqmllocalstorageplugin.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/qml/QtQuick/Particles.2/libparticlesplugin.prl:
/Users/marekflorianczyk/Felgo/Felgo/ios/qml/Qt/labs/settings/libqmlsettingsplugin.prl:
qmake: FORCE
	@$(QMAKE) -o felgo_statusbar.xcodeproj/project.pbxproj felgo_statusbar.pro -spec macx-xcode

qmake_all: FORCE

