#############################################################################
# Makefile for building: felgo_statusbar.app/Contents/MacOS/felgo_statusbar
# Generated by qmake (3.1) (Qt 5.15.2)
# Project:  felgo_statusbar.pro
# Template: app
# Command: /Users/marekflorianczyk/Felgo/Felgo/ios/bin/qmake -o felgo_statusbar.xcodeproj/project.pbxproj felgo_statusbar.pro -spec macx-xcode
#############################################################################

MAKEFILE      = project.pbxproj

EQ            = =

MOC       = /Users/marekflorianczyk/Felgo/Felgo/ios/bin/moc
UIC       = /Users/marekflorianczyk/Felgo/Felgo/ios/bin/uic
LEX       = flex
LEXFLAGS  = 
YACC      = yacc
YACCFLAGS = -d
DEFINES       = -DQT_COMPILER_SUPPORTS_SSE2 -DQT_QUICK_LIB -DQT_WIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_QMLMODELS_LIB -DQT_QML_LIB -DQT_WEBSOCKETS_LIB -DQT_NETWORK_LIB -DQT_SQL_LIB -DQT_BLUETOOTH_LIB -DQT_CORE_LIB
INCPATH       = -I. -I/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/common/uikit -I/Users/marekflorianczyk/Felgo/Felgo/ios/include/Felgo -I/Users/marekflorianczyk/Felgo/Felgo/ios/include -I/Users/marekflorianczyk/Felgo/Felgo/ios/include/QtQuick -I/Users/marekflorianczyk/Felgo/Felgo/ios/include/QtWidgets -I/Users/marekflorianczyk/Felgo/Felgo/ios/include/QtMultimedia -I/Users/marekflorianczyk/Felgo/Felgo/ios/include/QtGui -I/Users/marekflorianczyk/Felgo/Felgo/ios/include/QtQmlModels -I/Users/marekflorianczyk/Felgo/Felgo/ios/include/QtQml -I/Users/marekflorianczyk/Felgo/Felgo/ios/include/QtWebSockets -I/Users/marekflorianczyk/Felgo/Felgo/ios/include/QtNetwork -I/Users/marekflorianczyk/Felgo/Felgo/ios/include/QtSql -I/Users/marekflorianczyk/Felgo/Felgo/ios/include/QtBluetooth -I/Users/marekflorianczyk/Felgo/Felgo/ios/include/QtCore -I. -I/Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/macx-ios-clang
DEL_FILE  = rm -f
MOVE      = mv -f

preprocess: compilers
clean preprocess_clean: compiler_clean

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compilers: qrc_resources_user.cpp
compiler_rcc_make_all: qrc_resources_user.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources_user.cpp
qrc_resources_user.cpp: /Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/common/felgo/resources_user.qrc \
		/Users/marekflorianczyk/Felgo/Felgo/ios/bin/rcc \
		/Users/marekflorianczyk/Felgo/Felgo/felgo_license.key
	/Users/marekflorianczyk/Felgo/Felgo/ios/bin/rcc -name resources_user /Users/marekflorianczyk/Felgo/Felgo/ios/mkspecs/common/felgo/resources_user.qrc -o qrc_resources_user.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean 

